# Site settings
title: Drifting Fish Blog
header-img: img/home-bg.jpg
email: 1993sj1993@gmail.com
description: "Personal Blog"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  shenjie1993

# Build settings
markdown: kramdown
auto: true
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#Set personal info bar
sidebar-personal-desc: "Hello World"
sidebar-portrait: /img/portrait-drfish.jpg 
