# Site settings
title: Drifting Fish Blog
header-img: img/home-bg.jpg
description: "Personal Blog"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highligher: true
highlighter: rouge
permalink: pretty
paginate: 5

# Encoding settings
encoding: "utf-8"

# Plugins settings
plugins: [jekyll-paginate]
